In [ ]:
# Tests for Baseline Acquisition Functions

In [ ]:
# hide

import blackhc.project.script
from nbdev.showdoc import *

Appended /home/blackhc/PycharmProjects/bald-ical/src to paths
Switched to directory /home/blackhc/PycharmProjects/bald-ical
%load_ext autoreload
%autoreload 2


In [ ]:
import torch

from batchbald_redux import baseline_acquisition_functions

In [ ]:
baseline_acquisition_functions.get_variation_ratios(torch.randn(size=(7,13,10)), device="cpu")

tensor([-1.7019, -1.6160, -4.1097, -0.9801, -2.1539, -4.4987, -1.8911])

In [ ]:
baseline_acquisition_functions.get_margin_scores(torch.randn(size=(7,13,10)), device="cpu")

tensor([0.5793, 0.9042, 0.8619, 0.9185, 0.7739, 0.7329, 0.9758],
       dtype=torch.float64)

In [ ]:
baseline_acquisition_functions.get_stddev_scores(torch.randn(size=(7,13,10)), device="cpu")

tensor([21.7611, 15.6393, 17.3622, 15.8508, 13.1821, 16.7927, 12.5366],
       dtype=torch.float64)