In [ ]:
# Tests for Baseline Acquisition Functions

In [ ]:
# hide

import blackhc.project.script
from nbdev.showdoc import *

Appended /home/blackhc/PycharmProjects/bald-ical/src to paths
Switched to directory /home/blackhc/PycharmProjects/bald-ical
%load_ext autoreload
%autoreload 2


In [ ]:
import torch

from batchbald_redux import baseline_acquisition_functions

In [ ]:
baseline_acquisition_functions.get_variation_ratios(torch.randn(size=(7,13,10)), device="cpu")

tensor([-5, -6, -3, -4,  0, -3, -4])

In [ ]:
baseline_acquisition_functions.get_margin_scores(torch.randn(size=(7,13,10)), device="cpu")

tensor([0.2698, 0.2892])

In [ ]:
baseline_acquisition_functions.get_mean_stddev_scores(torch.randn(size=(7,13,10)), device="cpu")

tensor([1.6610, 1.6845, 1.2571, 1.0790, 1.2159, 1.9808, 1.4166])